#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════
# 🆓 FREE AI CLI — One-Click Setup
# Sets up FREE AI access from your terminal. No credit card needed.
# ═══════════════════════════════════════════════════════════════════════

set -e

BOLD='\033[1m'
CYAN='\033[36m'
GREEN='\033[32m'
YELLOW='\033[33m'
RED='\033[31m'
GRAY='\033[90m'
NC='\033[0m'

echo ""
echo -e "${CYAN}${BOLD}🆓 FREE AI CLI — One-Click Setup${NC}"
echo -e "${GRAY}Zero-cost AI access. No credit card. Permanent free tiers.${NC}"
echo ""

# ─── Step 1: Install Node.js dependencies ─────────────────────────────
echo -e "${BOLD}📦 Step 1: Installing dependencies...${NC}"
npm install -g @google/gemini-cli 2>/dev/null || true
echo -e "  ${GREEN}✅ Gemini CLI installed${NC}"
echo ""

# ─── Step 2: Install Ollama (optional, for local AI) ──────────────────
echo -e "${BOLD}🏠 Step 2: Local AI (optional but recommended)${NC}"
if command -v ollama &>/dev/null; then
    echo -e "  ${GREEN}✅ Ollama already installed${NC}"
else
    echo -e "  ${YELLOW}Installing Ollama for unlimited local AI...${NC}"
    curl -fsSL https://ollama.com/install.sh | sh 2>/dev/null || {
        echo -e "  ${YELLOW}⬜ Ollama install skipped (install manually from https://ollama.com)${NC}"
    }
fi

# Pull a small model for instant local AI
if command -v ollama &>/dev/null; then
    echo -e "  ${GRAY}Pulling Qwen3 8B (fast, good quality, ~5GB)...${NC}"
    ollama pull qwen3:8b 2>/dev/null &
    OLLAMA_PULL_PID=$!
fi
echo ""

# ─── Step 3: Get FREE API Keys ────────────────────────────────────────
echo -e "${BOLD}🔑 Step 3: Get your FREE API keys${NC}"
echo -e "${GRAY}Open these URLs in your browser and generate free API keys:${NC}"
echo ""
echo -e "  ${GREEN}1. Google AI Studio (Gemini)${NC} — BEST FREE API"
echo -e "     ${CYAN}https://aistudio.google.com/apikey${NC}"
echo -e "     ${GRAY}→ Gemini 2.5 Flash, 2.5 Pro, 1M context, image generation${NC}"
echo -e "     ${GRAY}→ 15 RPM / 1,500 RPD — most generous free tier${NC}"
echo ""
echo -e "  ${GREEN}2. Groq${NC} — FASTEST INFERENCE"
echo -e "     ${CYAN}https://console.groq.com${NC}"
echo -e "     ${GRAY}→ Llama 3.3 70B, Qwen3 32B, Kimi K2${NC}"
echo -e "     ${GRAY}→ 500+ tokens/sec, 30 RPM / 14,400 RPD${NC}"
echo ""
echo -e "  ${GREEN}3. Mistral${NC} — MOST GENEROUS QUOTA"
echo -e "     ${CYAN}https://console.mistral.ai${NC}"
echo -e "     ${GRAY}→ Mistral Large, Codestral, all models${NC}"
echo -e "     ${GRAY}→ ~1B tokens/month free (Experiment plan)${NC}"
echo ""
echo -e "  ${GREEN}4. Cerebras${NC} — ULTRA-FAST WAFER-SCALE"
echo -e "     ${CYAN}https://cloud.cerebras.ai${NC}"
echo -e "     ${GRAY}→ Llama 3.3 70B, Qwen 2.5 32B${NC}"
echo -e "     ${GRAY}→ 1.5M tokens/day, 30 RPM${NC}"
echo ""
echo -e "  ${GREEN}5. OpenRouter${NC} — 27+ FREE MODELS"
echo -e "     ${CYAN}https://openrouter.ai${NC}"
echo -e "     ${GRAY}→ DeepSeek, Llama, Qwen, Nemotron — all free${NC}"
echo -e "     ${GRAY}→ 20 RPM / 50 RPD${NC}"
echo ""
echo -e "  ${GREEN}6. DeepSeek${NC} — FRONTIER REASONING"
echo -e "     ${CYAN}https://platform.deepseek.com${NC}"
echo -e "     ${GRAY}→ DeepSeek V3, R1 — 5M free tokens on signup${NC}"
echo ""

# ─── Step 4: Configure API Keys ──────────────────────────────────────
echo -e "${BOLD}⚙️  Step 4: Configure your API keys${NC}"
echo -e "${GRAY}Paste your keys below (press Enter to skip any):${NC}"
echo ""

CONFIG_FILE="$HOME/.free-ai-env"

read -p "  Google AI Studio API Key: " GOOGLE_KEY
read -p "  Groq API Key: " GROQ_KEY
read -p "  Mistral API Key: " MISTRAL_KEY
read -p "  Cerebras API Key: " CEREBRAS_KEY
read -p "  OpenRouter API Key: " OPENROUTER_KEY
read -p "  DeepSeek API Key: " DEEPSEEK_KEY

# Write config file
cat > "$CONFIG_FILE" << EOF
# Free AI CLI — API Keys (all free, no credit card)
# Generated by setup-free-ai.sh

${GOOGLE_KEY:+export GOOGLE_AI_API_KEY="$GOOGLE_KEY"}
${GROQ_KEY:+export GROQ_API_KEY="$GROQ_KEY"}
${MISTRAL_KEY:+export MISTRAL_API_KEY="$MISTRAL_KEY"}
${CEREBRAS_KEY:+export CEREBRAS_API_KEY="$CEREBRAS_KEY"}
${OPENROUTER_KEY:+export OPENROUTER_API_KEY="$OPENROUTER_KEY"}
${DEEPSEEK_KEY:+export DEEPSEEK_API_KEY="$DEEPSEEK_KEY"}
EOF

# Add to shell config
SHELL_RC="$HOME/.bashrc"
if [[ -f "$HOME/.zshrc" ]]; then
    SHELL_RC="$HOME/.zshrc"
fi

if ! grep -q "free-ai-env" "$SHELL_RC" 2>/dev/null; then
    echo "" >> "$SHELL_RC"
    echo "# Free AI CLI" >> "$SHELL_RC"
    echo "source ~/.free-ai-env" >> "$SHELL_RC"
fi

source "$CONFIG_FILE"

echo ""
echo -e "${GREEN}${BOLD}✅ Setup Complete!${NC}"
echo ""

# ─── Step 5: Verify ──────────────────────────────────────────────────
echo -e "${BOLD}🩺 Verification:${NC}"
CONFIGURED=0

if [[ -n "$GOOGLE_AI_API_KEY" ]]; then
    echo -e "  ${GREEN}✅ Google AI Studio (Gemini)${NC}"
    ((CONFIGURED++))
else
    echo -e "  ${YELLOW}⬜ Google AI Studio — not configured${NC}"
fi

if [[ -n "$GROQ_API_KEY" ]]; then
    echo -e "  ${GREEN}✅ Groq${NC}"
    ((CONFIGURED++))
else
    echo -e "  ${YELLOW}⬜ Groq — not configured${NC}"
fi

if [[ -n "$MISTRAL_API_KEY" ]]; then
    echo -e "  ${GREEN}✅ Mistral${NC}"
    ((CONFIGURED++))
else
    echo -e "  ${YELLOW}⬜ Mistral — not configured${NC}"
fi

if [[ -n "$CEREBRAS_API_KEY" ]]; then
    echo -e "  ${GREEN}✅ Cerebras${NC}"
    ((CONFIGURED++))
else
    echo -e "  ${YELLOW}⬜ Cerebras — not configured${NC}"
fi

if [[ -n "$OPENROUTER_API_KEY" ]]; then
    echo -e "  ${GREEN}✅ OpenRouter${NC}"
    ((CONFIGURED++))
else
    echo -e "  ${YELLOW}⬜ OpenRouter — not configured${NC}"
fi

if [[ -n "$DEEPSEEK_API_KEY" ]]; then
    echo -e "  ${GREEN}✅ DeepSeek${NC}"
    ((CONFIGURED++))
else
    echo -e "  ${YELLOW}⬜ DeepSeek — not configured${NC}"
fi

if command -v ollama &>/dev/null; then
    echo -e "  ${GREEN}✅ Ollama (local, unlimited)${NC}"
    ((CONFIGURED++))
else
    echo -e "  ${YELLOW}⬜ Ollama — not installed${NC}"
fi

echo ""
echo -e "${BOLD}📊 ${CONFIGURED} providers configured${NC}"

# ─── Show Usage ──────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}${BOLD}🚀 Quick Start:${NC}"
echo ""
echo -e "  ${GRAY}# Chat with the best free model${NC}"
echo -e "  gemini \"Explain quantum computing\""
echo ""
echo -e "  ${GRAY}# Chat with specific model${NC}"
echo -e "  GEMINI_MODEL=gemini-2.5-flash gemini \"Quick question\""
echo ""
echo -e "  ${GRAY}# Use Groq for fastest responses${NC}"
echo -e "  curl -s https://api.groq.com/openai/v1/chat/completions \\"
echo -e "    -H \"Authorization: Bearer \$GROQ_API_KEY\" \\"
echo -e "    -H \"Content-Type: application/json\" \\"
echo -e "    -d '{\"model\":\"llama-3.3-70b-versatile\",\"messages\":[{\"role\":\"user\",\"content\":\"Hello\"}]}'"
echo ""
echo -e "  ${GRAY}# Use Ollama locally (unlimited, private)${NC}"
echo -e "  ollama run qwen3:8b \"Write a Python script\""
echo ""
echo -e "  ${GRAY}# Use Gemini CLI (free, 1M context)${NC}"
echo -e "  gemini  # Interactive mode"
echo ""

# Wait for Ollama model pull if it's running
if [[ -n "$OLLAMA_PULL_PID" ]]; then
    echo -e "${GRAY}Waiting for Ollama model download to complete...${NC}"
    wait "$OLLAMA_PULL_PID" 2>/dev/null
    echo -e "  ${GREEN}✅ Local model ready!${NC}"
fi

echo ""
echo -e "${CYAN}${BOLD}💰 Total cost: \$0.00 — forever.${NC}"
echo ""
